### ISSUE TITLE
UNAVAILABLE: ipv4:131.159.152.5:443

### ISSUE THREAD

**Issue by opible** [gagneurlab/spectralis#4]
Hi,
I am currently trying to test spectralis for de novo peptide sequencing of DDA datasets, and I currently have a problem.
While it is possible to get it running on a standard PC with open web connection after careful selection of python and packages versions,  the same setting copied to a server with limited web connection does not run...
 
The problem seems to be an access to 131.159.152.5:443 corresponding to https://www.proteomicsdb.org/ , port 443 ?? This seems like an access to Prosit … is spectralis using the Prosit online tool ?
If not can this access be inactivated in a way because we try to limit as much as possible server external server access… ?
 
Thank in advance,
Best,
 
STDOUT:
 
5000it [00:03, 1332.29it/s]
  0%|                                                                                            | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "E:\spectralis___denovo\test___denovo_mode\spectralis___denovo_test.py", line 32, in <module>
   spectralis.evo_algorithm_from_mgf(mgf_path=inname,output_path=oname)
  File "E:\spectralis___denovo\Python3.8.8\lib\site-packages\spectralis\spectralis_master.py", line 319, in evo_algorithm_from_mgf
    df_out = self.evo_algorithm(padded_seqs, precursor_z, precursor_m,
  File "E:\spectralis___denovo\Python3.8.8\lib\site-packages\spectralis\spectralis_master.py", line 478, in evo_algorithm
    return optimizer.run_optimization(seqs, precursor_z, precursor_m,
  File "E:\spectralis___denovo\Python3.8.8\lib\site-packages\spectralis\evolutionary_algorithm\ea_optimizer.py", line 400, in run_optimization
    out_determined = self.determine_passed_not_passed( initial_seqs, precursor_z, precursor_m, scans,
  File "E:\spectralis___denovo\Python3.8.8\lib\site-packages\spectralis\evolutionary_algorithm\ea_optimizer.py", line 196, in determine_passed_not_passed
    initial_scores = self.get_initial_scores(initial_seqs, precursor_z, precursor_m, scans,
  File "E:\spectralis___denovo\Python3.8.8\lib\site-packages\spectralis\evolutionary_algorithm\ea_optimizer.py", line 163, in get_initial_scores
    prosit_out = U.get_prosit_output(initial_seqs, precursor_z, self.PROSIT_CE )
  File "E:\spectralis___denovo\Python3.8.8\lib\site-packages\spectralis\denovo_utils\__utils__.py", line 71, in get_prosit_output
    prediction = triton_client.infer(model_name, inputs=koina_inputs, outputs=koina_outputs)
  File "E:\spectralis___denovo\Python3.8.8\lib\site-packages\tritonclient\grpc\_client.py", line 1572, in infer
    raise_error_grpc(rpc_error)
  File "E:\spectralis___denovo\Python3.8.8\lib\site-packages\tritonclient\grpc\_utils.py", line 77, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.UNAVAILABLE] failed to connect to all addresses; last error: UNAVAILABLE: ipv4:131.159.152.5:443: End of TCP stream

**Comment by CamiloPosso** [comment]
We're running into a similar issue. Looking at the function get_prosit_output in the __utils__.py file, it always connects to a server for its output. It seems the output is a theoretical spectrum generated from the peptide and charge by a tool called prosit, which is available to download and use locally.

We would also like to avoid connecting to other servers. I hope this prosit output is the only part where a server connection is needed, in that case I think modifying it to avoid this should be possible and straightforward. 

I would be really interested to hear from the creators of Spectralis on this.
